CREATE TABLE categories      (id VARCHAR(36) PRIMARY KEY, description VARCHAR(256));
CREATE TABLE anatomic_sites  (id VARCHAR(36) PRIMARY KEY, description VARCHAR(256));
CREATE TABLE diagnoses       (id VARCHAR(36) PRIMARY KEY, description VARCHAR(256));
CREATE TABLE subsites        (id VARCHAR(36) PRIMARY KEY, description VARCHAR(256));

CREATE TABLE dis_relationship_master (
    ID               VARCHAR(36) PRIMARY KEY,
    CATEGORY_ID      VARCHAR(36) CONSTRAINT CATEGORY_ID      REFERENCES categories (id),
    ANATOMIC_SITE_ID VARCHAR(36) CONSTRAINT ANATOMIC_SITE_ID REFERENCES anatomic_sites (id),
    DIAGNOSIS_ID     VARCHAR(36) CONSTRAINT DIAGNOSIS_ID     REFERENCES diagnoses (id)

CREATE TABLE dis_relationship_site_subsite (
    ANATOMIC_SITE_ID    VARCHAR(36) CONSTRAINT ANATOMIC_SITE_ID    REFERENCES anatomic_sites (id),
    ANATOMIC_SUBSITE_ID VARCHAR(36) CONSTRAINT ANATOMIC_SUBSITE_ID REFERENCES subsites (id)